In [205]:
from urllib.request import urlopen
from bs4 import BeautifulSoup
import pandas as pd
import sys
import io

In [262]:
url = "https://finance.naver.com/sise/"
page = urlopen(url)

soup = BeautifulSoup(page, "html.parser")

top_table = soup.find("table", id="siselist_tab_0")
top_table

<table cellpadding="0" cellspacing="0" class="type_2" id="siselist_tab_0" summary="탑종목 상한가 리스트">
<caption>상한가</caption>
<col width="4%"/>
<col width="4%"/>
<col width="4%"/>
<col width="*"/>
<col width="7%"/>
<col width="9%"/>
<col width="7%"/>
<col width="12%"/>
<col width="12%"/>
<col width="12%"/>
<col width="12%"/>
<tr>
<th>순위</th>
<th>연속</th>
<th>누적</th>
<th>종목명</th>
<th>현재가</th>
<th class="tr">전일비  </th>
<th>등락률</th>
<th>거래량</th>
<th>시가</th>
<th>고가</th>
<th>저가</th>
</tr>
<tr><td class="blank_08" colspan="10"></td></tr>
<tr>
<td class="tc"><img alt="01" height="11" src="https://ssl.pstatic.net/imgstock/images5/ico_n01.gif" width="11"/></td>
<td class="number">2</td>
<td class="number">4</td>
<td><a class="tltle" href="/item/main.nhn?code=006345" onclick="clickcr(this, 'bqu.2', '006345', '1', event)">대원전선우</a></td>
<td class="number">6,050</td>
<td class="number">
<em class="bu_p bu_pup2" style="margin:0 4px 0 0"><span class="blind">상한</span></em><span class="tah p11 red01">
				1,390
				</span>
</td>
<td class="number">
<span class="tah p11 red01">
				+29.83%
				</span>
</td>
<td class="number">860,445</td>
<td class="number">5,410</td>
<td class="number">6,050</td>
<td class="number">5,410</td>
</tr>
<tr>
<td class="tc"><img alt="01" height="11" src="https://ssl.pstatic.net/imgstock/images5/ico_n02.gif" width="11"/></td>
<td class="number">1</td>
<td class="number">1</td>
<td><a class="tltle" href="/item/main.nhn?code=036180" onclick="clickcr(this, 'bqu.2', '036180', '2', event)">지더블유바이텍</a></td>
<td class="number">3,130</td>
<td class="number">
<em class="bu_p bu_pup2" style="margin:0 4px 0 0"><span class="blind">상한</span></em><span class="tah p11 red01">
				720
				</span>
</td>
<td class="number">
<span class="tah p11 red01">
				+29.88%
				</span>
</td>
<td class="number">373,914</td>
<td class="number">2,410</td>
<td class="number">3,130</td>
<td class="number">2,410</td>
</tr>
<tr>
<td class="tc"><img alt="01" height="11" src="https://ssl.pstatic.net/imgstock/images5/ico_n03.gif" width="11"/></td>
<td class="number">1</td>
<td class="number">2</td>
<td><a class="tltle" href="/item/main.nhn?code=043910" onclick="clickcr(this, 'bqu.2', '043910', '3', event)">자연과환경</a></td>
<td class="number">2,780</td>
<td class="number">
<em class="bu_p bu_pup2" style="margin:0 4px 0 0"><span class="blind">상한</span></em><span class="tah p11 red01">
				640
				</span>
</td>
<td class="number">
<span class="tah p11 red01">
				+29.91%
				</span>
</td>
<td class="number">48,692,956</td>
<td class="number">2,205</td>
<td class="number">2,780</td>
<td class="number">2,195</td>
</tr>
<tr>
<td class="tc"><img alt="01" height="11" src="https://ssl.pstatic.net/imgstock/images5/ico_n04.gif" width="11"/></td>
<td class="number">1</td>
<td class="number">1</td>
<td><a class="tltle" href="/item/main.nhn?code=079940" onclick="clickcr(this, 'bqu.2', '079940', '4', event)">가비아</a></td>
<td class="number">19,100</td>
<td class="number">
<em class="bu_p bu_pup2" style="margin:0 4px 0 0"><span class="blind">상한</span></em><span class="tah p11 red01">
				4,400
				</span>
</td>
<td class="number">
<span class="tah p11 red01">
				+29.93%
				</span>
</td>
<td class="number">12,452,113</td>
<td class="number">14,800</td>
<td class="number">19,100</td>
<td class="number">14,500</td>
</tr>
<tr>
<td class="tc"><img alt="01" height="11" src="https://ssl.pstatic.net/imgstock/images5/ico_n05.gif" width="11"/></td>
<td class="number">1</td>
<td class="number">1</td>
<td><a class="tltle" href="/item/main.nhn?code=090150" onclick="clickcr(this, 'bqu.2', '090150', '5', event)">광진윈텍</a></td>
<td class="number">5,410</td>
<td class="number">
<em class="bu_p bu_pup2" style="margin:0 4px 0 0"><span class="blind">상한</span></em><span class="tah p11 red01">
				1,245
				</span>
</td>
<td class="number">
<span class="tah p11 red01">
				+29.89%
				</span>
</td>
<td class="number">1,233,708</td>
<td class="number">4,780</td>
<td class="number">5,410</td>
<td class="number">4,530</td>
</tr>
<tr><td class="blank_06" colspan="10"></td></tr>
<tr><td class="division_line" colspan="10"></td></tr>
<tr><td class="blank_08" colspan="10"></td></tr>
<tr>
<td class="tc"><img alt="01" height="11" src="https://ssl.pstatic.net/imgstock/images5/ico_n06.gif" width="11"/></td>
<td class="number">1</td>
<td class="number">3</td>
<td><a class="tltle" href="/item/main.nhn?code=130660" onclick="clickcr(this, 'bqu.2', '130660', '6', event)">한전산업</a></td>
<td class="number">11,100</td>
<td class="number">
<em class="bu_p bu_pup2" style="margin:0 4px 0 0"><span class="blind">상한</span></em><span class="tah p11 red01">
				2,550
				</span>
</td>
<td class="number">
<span class="tah p11 red01">
				+29.82%
				</span>
</td>
<td class="number">36,451,207</td>
<td class="number">8,500</td>
<td class="number">11,100</td>
<td class="number">8,420</td>
</tr>
<tr>
<td class="tc"><img alt="01" height="11" src="https://ssl.pstatic.net/imgstock/images5/ico_n07.gif" width="11"/></td>
<td class="number">1</td>
<td class="number">9</td>
<td><a class="tltle" href="/item/main.nhn?code=311060" onclick="clickcr(this, 'bqu.2', '311060', '7', event)">엘에이티</a></td>
<td class="number">4,380</td>
<td class="number">
<em class="bu_p bu_pup2" style="margin:0 4px 0 0"><span class="blind">상한</span></em><span class="tah p11 red01">
				570
				</span>
</td>
<td class="number">
<span class="tah p11 red01">
				+14.96%
				</span>
</td>
<td class="number">209</td>
<td class="number">3,810</td>
<td class="number">4,380</td>
<td class="number">3,255</td>
</tr>
<tr><td class="blank_06" colspan="10"></td></tr>
<tr><td class="division_line" colspan="10"></td></tr>
</table>

In [263]:
# 컬럼 인덱스 추출

columns_info = top_table.find("tr")
columns_names = columns_info.find_all("th")
column_index = []
for column in columns_names:
    column_index.append(column.text)
column_index.pop(0)

'순위'

In [264]:
# 1위부터 5위까지 정보

tr_list = top_table.find_all("tr")
stock_info = []
for i in range(2, 7):
    one_stock_info = []
    td_list = tr_list[i].find_all("td")
    for td in td_list:
        one_stock_info.append(td.text)
    stock_info.append(one_stock_info)
print(stock_info)

[['', '2', '4', '대원전선우', '6,050', '\n상한\n\t\t\t\t1,390\n\t\t\t\t\n', '\n\n\t\t\t\t+29.83%\n\t\t\t\t\n', '860,445', '5,410', '6,050', '5,410'], ['', '1', '1', '지더블유바이텍', '3,130', '\n상한\n\t\t\t\t720\n\t\t\t\t\n', '\n\n\t\t\t\t+29.88%\n\t\t\t\t\n', '373,914', '2,410', '3,130', '2,410'], ['', '1', '2', '자연과환경', '2,780', '\n상한\n\t\t\t\t640\n\t\t\t\t\n', '\n\n\t\t\t\t+29.91%\n\t\t\t\t\n', '48,692,956', '2,205', '2,780', '2,195'], ['', '1', '1', '가비아', '19,100', '\n상한\n\t\t\t\t4,400\n\t\t\t\t\n', '\n\n\t\t\t\t+29.93%\n\t\t\t\t\n', '12,452,113', '14,800', '19,100', '14,500'], ['', '1', '1', '광진윈텍', '5,410', '\n상한\n\t\t\t\t1,245\n\t\t\t\t\n', '\n\n\t\t\t\t+29.89%\n\t\t\t\t\n', '1,233,708', '4,780', '5,410', '4,530']]

In [265]:
# 6위 & 7위 정보

tr_list = top_table.find_all("tr")

for i in [10, 11]:
    one_stock_info = []
    td_list = tr_list[i].find_all("td")
    for td in td_list:
        one_stock_info.append(td.text)
    stock_info.append(one_stock_info)
print(stock_info)

[['', '2', '4', '대원전선우', '6,050', '\n상한\n\t\t\t\t1,390\n\t\t\t\t\n', '\n\n\t\t\t\t+29.83%\n\t\t\t\t\n', '860,445', '5,410', '6,050', '5,410'], ['', '1', '1', '지더블유바이텍', '3,130', '\n상한\n\t\t\t\t720\n\t\t\t\t\n', '\n\n\t\t\t\t+29.88%\n\t\t\t\t\n', '373,914', '2,410', '3,130', '2,410'], ['', '1', '2', '자연과환경', '2,780', '\n상한\n\t\t\t\t640\n\t\t\t\t\n', '\n\n\t\t\t\t+29.91%\n\t\t\t\t\n', '48,692,956', '2,205', '2,780', '2,195'], ['', '1', '1', '가비아', '19,100', '\n상한\n\t\t\t\t4,400\n\t\t\t\t\n', '\n\n\t\t\t\t+29.93%\n\t\t\t\t\n', '12,452,113', '14,800', '19,100', '14,500'], ['', '1', '1', '광진윈텍', '5,410', '\n상한\n\t\t\t\t1,245\n\t\t\t\t\n', '\n\n\t\t\t\t+29.89%\n\t\t\t\t\n', '1,233,708', '4,780', '5,410', '4,530'], ['', '1', '3', '한전산업', '11,100', '\n상한\n\t\t\t\t2,550\n\t\t\t\t\n', '\n\n\t\t\t\t+29.82%\n\t\t\t\t\n', '36,451,207', '8,500', '11,100', '8,420'], ['', '1', '9', '엘에이티', '4,380', '\n상한\n\t\t\t\t570\n\t\t\t\t\n', '\n\n\t\t\t\t+14.96%\n\t\t\t\t\n', '209', '3,810', '4,380', '3,255']]

In [266]:
stock_final = {}
n = 1
for stock in stock_info:
    
    stock.pop(0)
    stock[4] = stock[4].replace("\n", "")
    stock[4] = stock[4].replace("\t", "")
    
    stock[5] = stock[5].replace("\n", "")
    stock[5] = stock[5].replace("\t", "")
    
    stock_final[n] = stock
    n += 1
    
print(stock_final)

{1: ['2', '4', '대원전선우', '6,050', '상한1,390', '+29.83%', '860,445', '5,410', '6,050', '5,410'], 2: ['1', '1', '지더블유바이텍', '3,130', '상한720', '+29.88%', '373,914', '2,410', '3,130', '2,410'], 3: ['1', '2', '자연과환경', '2,780', '상한640', '+29.91%', '48,692,956', '2,205', '2,780', '2,195'], 4: ['1', '1', '가비아', '19,100', '상한4,400', '+29.93%', '12,452,113', '14,800', '19,100', '14,500'], 5: ['1', '1', '광진윈텍', '5,410', '상한1,245', '+29.89%', '1,233,708', '4,780', '5,410', '4,530'], 6: ['1', '3', '한전산업', '11,100', '상한2,550', '+29.82%', '36,451,207', '8,500', '11,100', '8,420'], 7: ['1', '9', '엘에이티', '4,380', '상한570', '+14.96%', '209', '3,810', '4,380', '3,255']}

In [269]:
top_stock_df = pd.DataFrame(stock_final).transpose()

   0  1        2       3        4        5           6       7       8       9
1  2  4    대원전선우   6,050  상한1,390  +29.83%     860,445   5,410   6,050   5,410
2  1  1  지더블유바이텍   3,130    상한720  +29.88%     373,914   2,410   3,130   2,410
3  1  2    자연과환경   2,780    상한640  +29.91%  48,692,956   2,205   2,780   2,195
4  1  1      가비아  19,100  상한4,400  +29.93%  12,452,113  14,800  19,100  14,500
5  1  1     광진윈텍   5,410  상한1,245  +29.89%   1,233,708   4,780   5,410   4,530
6  1  3     한전산업  11,100  상한2,550  +29.82%  36,451,207   8,500  11,100   8,420
7  1  9     엘에이티   4,380    상한570  +14.96%         209   3,810   4,380   3,255

In [270]:
top_stock_df.columns = column_index
top_stock_df

  연속 누적      종목명     현재가    전일비        등락률         거래량      시가      고가      저가
1  2  4    대원전선우   6,050  상한1,390  +29.83%     860,445   5,410   6,050   5,410
2  1  1  지더블유바이텍   3,130    상한720  +29.88%     373,914   2,410   3,130   2,410
3  1  2    자연과환경   2,780    상한640  +29.91%  48,692,956   2,205   2,780   2,195
4  1  1      가비아  19,100  상한4,400  +29.93%  12,452,113  14,800  19,100  14,500
5  1  1     광진윈텍   5,410  상한1,245  +29.89%   1,233,708   4,780   5,410   4,530
6  1  3     한전산업  11,100  상한2,550  +29.82%  36,451,207   8,500  11,100   8,420
7  1  9     엘에이티   4,380    상한570  +14.96%         209   3,810   4,380   3,255

In [271]:
top_stock_df.to_csv("Top 종목 상한가 정보.csv")
top_stock_df.to_excel("Top 종목 상한가 정보.xlsx")