In [1]:
from IPython.display import display, Image
import os, warnings
import re
warnings.filterwarnings(action='ignore')

from selenium import webdriver
from bs4 import BeautifulSoup

driver = webdriver.Chrome('./chromedriver_90')
url = 'https://coronaboard.kr/'
driver.get(url)

import time
time.sleep(3)  # 홈페이지 로딩 시간 3초

from selenium.webdriver import ActionChains

some_tag = driver.find_element_by_id('show-more')
ActionChains(driver).move_to_element(some_tag).perform()
some_tag.click()

In [2]:
show_more_btn = driver.find_element_by_xpath('//*[@id="show-more"]')
show_more_btn.click()

In [3]:
t_body = driver.find_element_by_tag_name("tbody")

##### //*[@id="country-table"]/div/div/table/tbody/tr[1]/td[2] # 국가명
##### //*[@id="country-table"]/div/div/table/tbody/tr[1]/td[3] # 확진자
##### //*[@id="country-table"]/div/div/table/tbody/tr[1]/td[8] # 발생률

In [4]:
row_data = t_body.find_elements_by_tag_name("tr")
one_row = row_data[0].find_elements_by_tag_name("td")

In [5]:
# 인덱스, 국가명, 확진자, 사망자, 완치, 치명%, 완치%, 발생률
data_container = []
country_data = []
for i in range(len(one_row)):
    country_data.append(one_row[i].text)
data_container.append(country_data)

In [6]:
data_container

[['1',
  '미국🇺🇸',
  '34,434,803\n(+14,822)',
  '617,875\n(+392)',
  '28,817,134\n(+48,726)',
  '1.8',
  '83.7',
  '104,032']]

In [7]:
# 전체 테이블 정보 행 단위 기준으로 크롤링해보기

row_data = t_body.find_elements_by_tag_name("tr")
all_data = []

for one_row in row_data:# 221번
    country_data_per_row = []
    all_tds = one_row.find_elements_by_tag_name("td")
    
    for i in range(8): # 8번
        country_data_per_row.append(all_tds[i].text)
    
    all_data.append(country_data_per_row)
    print(country_data_per_row)

['1', '미국🇺🇸', '34,434,803\n(+14,822)', '617,875\n(+392)', '28,817,134\n(+48,726)', '1.8', '83.7', '104,032']
['2', '인도🇮🇳', '30,027,850\n(+25,159)', '390,691\n(+1,030)', '28,987,311\n(+36,585)', '1.3', '96.5', '21,759']
['3', '브라질🇧🇷', '18,056,639\n(+86,833)', '504,897\n(+2,080)', '16,388,847\n(+100,455)', '2.8', '90.8', '84,949']
['4', '프랑스🇫🇷', '5,760,002\n(+2,204)', '110,829\n(+51)', '5,575,086\n(+8,692)', '1.9', '96.8', '88,244']
['5', '터키🇹🇷', '5,381,736\n(+6,143)', '49,293\n(+57)', '5,242,945\n(+5,214)', '0.9', '97.4', '63,811']
['6', '러시아🇷🇺', '5,350,919', '130,347', '4,889,450', '2.4', '91.4', '36,667']
['7', '영국🇬🇧', '4,651,988\n(+11,481)', '128,008\n(+27)', '4,306,482\n(+2,486)', '2.8', '92.6', '68,526']
['8', '아르헨티나🇦🇷', '4,298,782\n(+21,387)', '90,281\n(+791)', '3,928,389\n(+17,554)', '2.1', '91.4', '95,115']
['9', '이탈리아🇮🇹', '4,254,294\n(+834)', '127,322\n(+31)', '4,054,008\n(+4,692)', '3.0', '95.3', '70,363']
['10', '콜롬비아🇨🇴', '3,997,021\n(+28,616)', '101,302\n(+720)', '3,714,962\n(+29,015)', '2.5', '92.9', '78,553']
['11', '스페인🇪🇸', '3,768,691\n(+4,040)', '80,719\n(+30)', '3,564,850\n(+4,816)', '2.1', '94.6', '80,605']
['12', '독일🇩🇪', '3,731,287\n(+513)', '91,082\n(+57)', '3,608,100', '2.4', '96.7', '44,535']
['13', '이란🇮🇷', '3,117,336', '83,217', '2,771,705', '2.7', '88.9', '37,114']
['14', '폴란드🇵🇱', '2,879,030', '74,858', '2,650,773', '2.6', '92.1', '76,071']
['15', '멕시코🇲🇽', '2,482,784\n(+4,233)', '231,505\n(+261)', '1,977,071\n(+2,816)', '9.3', '79.6', '19,256']
['16', '우크라이나🇺🇦', '2,230,142', '52,053', '2,152,969', '2.3', '96.5', '50,994']
['17', '페루🇵🇪', '2,030,611', '190,645', 'N/A', '9.4', 'N/A', '61,586']
['18', '인도네시아🇮🇩', '2,018,113', '55,291', '1,810,136', '2.7', '89.7', '7,378']
['19', '남아프리카 공화국🇿🇦', '1,843,572\n(+11,093)', '59,092\n(+297)', '1,665,540\n(+8,860)', '3.2', '90.3', '31,084']
['20', '네덜란드🇳🇱', '1,680,228', '17,730', 'N/A', '1.1', 'N/A', '98,059']
['21', '체코🇨🇿', '1,666,192', '30,283', '1,633,482', '1.8', '98.0', '155,588']
['22', '칠레🇨🇱', '1,525,663\n(+3,440)', '31,690\n(+45)', '1,456,672\n(+4,564)', '2.1', '95.5', '79,810']
['23', '캐나다🇨🇦', '1,410,206\n(+599)', '26,155\n(+71)', '1,373,889\n(+1,398)', '1.9', '97.4', '37,364']
['24', '필리핀🇵🇭', '1,367,894', '23,809', '1,291,389', '1.7', '94.4', '12,483']
['25', '이라크🇮🇶', '1,298,703', '16,935', '1,209,918', '1.3', '93.2', '32,288']
['26', '스웨덴🇸🇪', '1,088,014', '14,570', 'N/A', '1.3', 'N/A', '107,732']
['27', '루마니아🇷🇴', '1,080,323', '32,465', '1,045,303', '3.0', '96.8', '56,157']
['28', '벨기에🇧🇪', '1,079,640', '25,141', '1,016,574', '2.3', '94.2', '93,156']
['29', '파키스탄🇵🇰', '949,838', '22,034', '894,352', '2.3', '94.2', '4,300']
['30', '포르투갈🇵🇹', '866,826', '17,074', '821,374', '2.0', '94.8', '85,010']
['31', '방글라데시🇧🇩', '861,150', '13,702', '788,385', '1.6', '91.6', '5,229']
['32', '이스라엘🇮🇱', '840,079\n(+47)', '6,428', '833,174\n(+4)', '0.8', '99.2', '97,057']
['33', '헝가리🇭🇺', '807,684', '29,963', '735,937', '3.7', '91.1', '83,608']
['34', '일본🇯🇵*', '785,969', '14,439', '749,282', '1.8', '95.3', '6,214']
['35', '요르단🇯🇴', '747,504\n(+504)', '9,683\n(+12)', '731,418\n(+587)', '1.3', '97.8', '73,262']
['36', '세르비아🇷🇸', '715,913', '7,010', '706,203', '1.0', '98.6', '81,937']
['37', '말레이시아🇲🇾', '705,762', '4,554', '639,181', '0.6', '90.6', '21,806']
['38', '스위스🇨🇭', '702,124', '10,875', '676,494', '1.5', '96.3', '81,127']
['39', '오스트리아🇦🇹', '649,728', '10,684', '636,523', '1.6', '98.0', '72,141']
['40', '네팔🇳🇵', '626,343', '8,813', '564,882', '1.4', '90.2', '21,497']
['41', '아랍에미레이트🇦🇪', '616,160\n(+2,167)', '1,767\n(+4)', '595,086\n(+2,102)', '0.3', '96.6', '62,299']
['42', '레바논🇱🇧', '543,698\n(+147)', '7,829\n(+4)', '530,689\n(+296)', '1.4', '97.6', '79,658']
['43', '모로코🇲🇦', '527,174\n(+437)', '9,247\n(+3)', '514,279\n(+381)', '1.8', '97.6', '14,282']
['44', '사우디아라비아🇸🇦', '476,882\n(+1,479)', '7,691', '458,048\n(+920)', '1.6', '96.1', '13,698']
['45', '에콰도르🇪🇨', '447,176\n(+543)', '21,315\n(+11)', '415,508', '4.8', '92.9', '25,346']
['46', '볼리비아🇧🇴', '424,478\n(+1,667)', '16,243\n(+69)', '344,609\n(+3,650)', '3.8', '81.2', '36,364']
['47', '불가리아🇧🇬', '421,246\n(+94)', '18,008\n(+8)', '393,636\n(+450)', '4.3', '93.4', '60,624']
['48', '그리스🇬🇷', '418,943\n(+395)', '12,575\n(+16)', '400,611\n(+733)', '3.0', '95.6', '40,194']
['49', '벨라루스🇧🇾', '411,551', '3,063', '404,240', '0.7', '98.2', '43,553']
['50', '카자흐스탄🇰🇿', '410,523', '4,249', '386,127', '1.0', '94.1', '21,863']
['51', '파라과이🇵🇾', '409,467\n(+1,746)', '11,849\n(+106)', '349,337\n(+2,691)', '2.9', '85.3', '57,408']
['52', '파나마🇵🇦', '395,449\n(+1,208)', '6,483\n(+6)', '378,109\n(+866)', '1.6', '95.6', '91,650']
['53', '슬로바키아🇸🇰', '391,385', '12,502', '378,044', '3.2', '96.6', '71,687']
['54', '튀니지🇹🇳', '387,773\n(+2,345)', '14,223\n(+105)', '339,065\n(+2,413)', '3.7', '87.4', '32,810']
['55', '조지아🇬🇪', '360,055', '5,199', '346,217', '1.4', '96.2', '90,258']
['56', '크로아티아🇭🇷', '359,259', '8,188', '350,539', '2.3', '97.6', '87,512']
['57', '우루과이🇺🇾', '358,461\n(+2,079)', '5,350\n(+34)', '329,662\n(+2,791)', '1.5', '92.0', '103,192']
['58', '코스타리카🇨🇷', '355,620\n(+1,525)', '4,546\n(+16)', '281,042\n(+2,817)', '1.3', '79.0', '69,810']
['59', '쿠웨이트🇰🇼', '342,929\n(+1,962)', '1,888\n(+11)', '322,897\n(+1,604)', '0.6', '94.2', '80,301']
['60', '아제르바이잔🇦🇿', '335,568\n(+47)', '4,963', '329,710\n(+111)', '1.5', '98.3', '33,096']
['61', '도미니카 공화국🇩🇴', '318,368\n(+723)', '3,769\n(+11)', '260,533\n(+884)', '1.2', '81.8', '29,348']
['62', '팔레스타인🇵🇸', '313,015\n(+204)', '3,555\n(+1)', '306,532\n(+220)', '1.1', '97.9', '61,358']
['63', '덴마크🇩🇰', '291,956', '2,531', '285,375', '0.9', '97.7', '50,405']
['64', '과테말라🇬🇹', '282,713\n(+1,859)', '8,785\n(+50)', '255,996\n(+1,296)', '3.1', '90.5', '15,780']
['65', '리투아니아🇱🇹', '278,466', '4,371', '265,966', '1.6', '95.5', '102,291']
['66', '이집트🇪🇬', '278,295\n(+498)', '15,935\n(+37)', '206,852\n(+799)', '5.7', '74.3', '2,719']
['67', '에티오피아🇪🇹', '275,391\n(+73)', '4,290\n(+4)', '255,962\n(+460)', '1.6', '92.9', '2,395']
['68', '아일랜드🇮🇪', '269,495\n(+174)', '4,979', '253,726\n(+438)', '1.8', '94.1', '54,578']
['69', '바레인🇧🇭', '263,689\n(+394)', '1,326\n(+15)', '256,063\n(+1,150)', '0.5', '97.1', '154,968']
['70', '베네수엘라🇻🇪', '263,372\n(+1,334)', '2,989\n(+16)', '243,840\n(+1,483)', '1.1', '92.6', '9,262']
['71', '슬로베니아🇸🇮', '257,066', '4,416', '251,243', '1.7', '97.7', '123,653']
['72', '몰도바🇲🇩', '256,232\n(+45)', '6,175\n(+2)', '249,250\n(+34)', '2.4', '97.3', '63,519']
['73', '온두라스🇭🇳', '255,117\n(+923)', '6,818\n(+46)', '91,943\n(+81)', '2.7', '36.0', '25,757']
['74', '오만🇴🇲', '252,609', '2,782', '221,250', '1.1', '87.6', '49,467']
['75', '스리랑카🇱🇰', '243,913\n(+2,093)', '2,704\n(+71)', '209,296\n(+7,907)', '1.1', '85.8', '11,391']
['76', '태국🇹🇭', '228,539\n(+3,174)', '1,744\n(+51)', '189,777\n(+1,941)', '0.8', '83.0', '3,274']
['77', '아르메니아🇦🇲', '224,330', '4,502', '216,182', '2.0', '96.4', '75,704']
['78', '카타르🇶🇦', '221,119', '584', '218,584', '0.3', '98.9', '76,749']
['79', '보스니아 헤르체고비나🇧🇦', '204,886\n(+26)', '9,648\n(+5)', '180,643\n(+398)', '4.7', '88.2', '62,450']
['80', '리비아🇱🇾', '191,253', '3,181', '176,649', '1.7', '92.4', '27,834']
['81', '케냐🇰🇪', '179,876\n(+583)', '3,484\n(+23)', '123,050\n(+85)', '1.9', '68.4', '3,345']
['82', '쿠바🇨🇺', '170,854\n(+1,489)', '1,180\n(+10)', '160,956\n(+1,181)', '0.7', '94.2', '15,084']
['83', '나이지리아🇳🇬', '167,331\n(+39)', '2,118', '163,913\n(+116)', '1.3', '98.0', '812']
['84', '북마케도니아🇲🇰', '155,640\n(+13)', '5,477', '149,908\n(+31)', '3.5', '96.3', '74,706']
['85', '대한민국🇰🇷', '152,545\n(+645)', '2,007\n(+1)', '144,379\n(+562)', '1.3', '94.6', '2,975']
['86', '미얀마🇲🇲', '149,247\n(+630)', '3,267\n(+2)', '133,893\n(+140)', '2.2', '89.7', '2,743']
['87', '라트비아🇱🇻', '136,975', '2,497', '132,721', '1.8', '96.9', '72,620']
['88', '알제리🇩🇿', '136,679\n(+385)', '3,650\n(+9)', '95,084\n(+262)', '2.7', '69.6', '3,117']
['89', '잠비아🇿🇲', '133,659', '1,744', '111,844', '1.3', '83.7', '7,270']
['90', '알바니아🇦🇱', '132,496\n(+5)', '2,455', '129,941\n(+12)', '1.9', '98.1', '46,041']
['91', '에스토니아🇪🇪', '130,855', '1,269', '126,798', '1.0', '96.9', '98,644']
['92', '노르웨이🇳🇴', '129,766\n(+221)', '790', '88,952', '0.6', '68.5', '23,937']

['93', '키르기스스탄🇰🇬', '116,546', '1,945', '105,932', '1.7', '90.9', '17,864']
['94', '아프가니스탄🇦🇫', '107,957', '4,366', '65,565', '4.0', '60.7', '2,773']
['95', '코소보🇽🇰', '107,247', '2,256', '105,025', '2.1', '97.9', '59,237']
['96', '우즈베키스탄🇺🇿', '106,847', '720', '102,546', '0.7', '96.0', '3,192']
['97', '몬테네그로🇲🇪', '100,104\n(+12)', '1,606\n(+1)', '98,202\n(+13)', '1.6', '98.1', '159,385']
['98', '몽골🇲🇳', '98,050', '459', '64,354', '0.5', '65.6', '29,909']
['99', '가나🇬🇭', '95,236\n(+177)', '794', '93,141\n(+136)', '0.8', '97.8', '3,065']
['100', '핀란드🇫🇮', '94,489', '967', '46,000', '1.0', '48.7', '17,054']
['101', '중국🇨🇳', '91,653\n(+24)', '4,636', '86,503\n(+22)', '5.1', '94.4', '64']
['102', '카메룬🇨🇲', '80,487\n(+159)', '1,320\n(+7)', '78,224\n(+62)', '1.6', '97.2', '3,032']
['103', '엘살바도르🇸🇻', '77,484', '2,341', '71,603', '3.0', '92.4', '11,946']
['104', '나미비아🇳🇦', '75,766', '1,179', '60,484', '1.6', '79.8', '29,819']
['105', '키프로스🇨🇾', '73,832\n(+122)', '374', '72,083', '0.5', '97.6', '61,152']
['106', '우간다🇺🇬', '73,401\n(+722)', '714\n(+34)', '50,085\n(+291)', '1.0', '68.2', '1,605']
['107', '모잠비크🇲🇿', '72,775\n(+198)', '852\n(+4)', '70,289\n(+48)', '1.2', '96.6', '2,328']
['108', '몰디브🇲🇻', '72,294\n(+145)', '207\n(+1)', '67,507\n(+359)', '0.3', '93.4', '133,743']
['109', '룩셈부르크🇱🇺', '70,547\n(+12)', '818', '69,461\n(+2)', '1.2', '98.5', '112,699']
['110', '보츠와나🇧🇼', '65,808', '1,069', '59,616', '1.6', '90.6', '27,984']
['111', '싱가포르🇸🇬', '62,448', '35', '62,098\n(+28)', '0.1', '99.4', '10,674']
['112', '자메이카🇯🇲', '49,735\n(+23)', '1,037\n(+3)', '28,935\n(+142)', '2.1', '58.2', '16,796']
['113', '코트디부아르🇨🇮', '48,058\n(+11)', '309\n(+1)', '47,511\n(+24)', '0.6', '98.9', '1,822']
['114', '캄보디아🇰🇭', '44,124', '459', '38,766', '1.0', '87.9', '2,639']
['115', '짐바브웨🇿🇼', '42,714\n(+519)', '1,691\n(+6)', '37,288\n(+88)', '4.0', '87.3', '2,874']
['116', '세네갈🇸🇳', '42,472', '1,159', '40,963', '2.7', '96.4', '2,537']
['117', '마다가스카르🇲🇬', '42,137', '903', '40,469', '2.1', '96.0', '1,522']
['118', '콩고민주공화국🇨🇩', '38,330', '888', '27,969', '2.3', '73.0', '428']
['119', '앙골라🇦🇴', '37,874\n(+126)', '875\n(+7)', '32,003\n(+221)', '2.3', '84.5', '1,152']
['120', '수단🇸🇩', '36,522\n(+175)', '2,748\n(+11)', '30,370\n(+308)', '7.5', '83.2', '833']
['121', '말라위🇲🇼', '34,996\n(+82)', '1,173\n(+2)', '32,909\n(+18)', '3.4', '94.0', '1,829']
['122', '르완다🇷🇼', '32,296\n(+861)', '392\n(+4)', '26,712\n(+8)', '1.2', '82.7', '2,493']
['123', '카보베르데🇨🇻', '32,111\n(+72)', '284\n(+1)', '31,138\n(+47)', '0.9', '97.0', '57,755']
['124', '트리니다드 토바고🇹🇹', '30,982\n(+215)', '761\n(+14)', '22,267\n(+395)', '2.5', '71.9', '22,138']
['125', '몰타 공화국🇲🇹', '30,595', '420', '30,148', '1.4', '98.5', '69,291']
['126', '호주🇦🇺', '30,380\n(+14)', '910', '29,272', '3.0', '96.4', '1,191']
['127', '레위니옹🇷🇪', '29,502\n(+1,061)', '226\n(+6)', '27,585\n(+1,252)', '0.8', '93.5', '32,952']
['128', '프랑스령 기아나🇬🇫', '26,799\n(+152)', '142', '9,995', '0.5', '37.3', '89,724']
['129', '시리아🇸🇾', '25,205\n(+47)', '1,851\n(+3)', '21,756\n(+9)', '7.3', '86.3', '1,440']
['130', '가봉🇬🇦', '24,885\n(+21)', '158', '24,407\n(+143)', '0.6', '98.1', '11,181']
['131', '기니🇬🇳', '23,543\n(+8)', '168', '22,340\n(+58)', '0.7', '94.9', '1,793']
['132', '모리타니🇲🇷', '20,415\n(+50)', '482\n(+1)', '19,477\n(+39)', '2.4', '95.4', '4,391']
['133', '수리남🇸🇷', '20,298\n(+157)', '477\n(+10)', '15,518\n(+94)', '2.3', '76.5', '34,601']
['134', '마요트🇾🇹', '19,389', '174', '2,964', '0.9', '15.3', '71,070']
['135', '가이아나🇬🇾', '19,234\n(+90)', '452\n(+3)', '17,241\n(+66)', '2.4', '89.6', '24,454']
['136', '프랑스령 폴리네시아🇵🇫', '18,981\n(+9)', '142', '18,814\n(+9)', '0.7', '99.1', '67,570']
['137', '에스와티니🇸🇿', '18,854\n(+23)', '677', '18,048\n(+9)', '3.6', '95.7', '16,251']
['138', '아이티🇭🇹', '17,710', '393', '12,753', '2.2', '72.0', '1,553']
['139', '파푸아뉴기니🇵🇬', '17,013', '173', '16,396', '1.0', '96.4', '1,902']
['140', '과들루프🇬🇵', '16,752', '229', '2,250', '1.4', '13.4', '41,867']
['141', '소말리아🇸🇴', '14,868\n(+1)', '775', '7,216\n(+12)', '5.2', '48.5', '935']
['142', '세이셸🇸🇨', '14,620', '59', '13,323', '0.4', '91.1', '148,657']
['143', '말리🇲🇱', '14,385', '524', '10,036', '3.6', '69.8', '710']
['144', '대만🇹🇼', '14,157\n(+2)', '575\n(+6)', '8,087\n(+553)', '4.1', '57.1', '594']
['145', '안도라🇦🇩', '13,864', '127', '13,665', '0.9', '98.6', '179,434']
['146', '베트남🇻🇳', '13,782\n(+152)', '69', '5,546\n(+93)', '0.5', '40.2', '142']
['147', '토고🇹🇬', '13,735\n(+4)', '128', '13,362\n(+4)', '0.9', '97.3', '1,659']
['148', '부르키나파소🇧🇫', '13,469', '168\n(+1)', '13,295\n(+2)', '1.2', '98.7', '644']
['149', '타지키스탄🇹🇯', '13,308', '90', '13,218', '0.7', '99.3', '1,395']
['150', '벨리즈🇧🇿', '13,059\n(+20)', '329', '12,572\n(+4)', '2.5', '96.3', '32,842']
['151', '콩고공화국🇨🇬', '12,404\n(+106)', '164\n(+3)', '11,211', '1.3', '90.4', '2,248']
['152', '바하마🇧🇸', '12,379\n(+15)', '244\n(+1)', '11,356\n(+34)', '2.0', '91.7', '31,479']
['153', '퀴라소🇨🇼', '12,321\n(+2)', '125', '12,163\n(+2)', '1.0', '98.7', '75,085']
['154', '마르티니크🇲🇶', '12,264\n(+86)', '98', '98', '0.8', '0.8', '32,681']
['155', '홍콩🇭🇰', '11,896', '210', '11,618\n(+2)', '1.8', '97.7', '1,587']
['156', '지부티🇩🇯', '11,595\n(+4)', '155', '11,434\n(+3)', '1.3', '98.6', '11,736']
['157', '레소토🇱🇸', '11,128\n(+21)', '329', '6,445', '3.0', '57.9', '5,195']
['158', '아루바🇦🇼', '11,116\n(+4)', '107', '10,978\n(+3)', '1.0', '98.8', '104,116']
['159', '남수단🇸🇸', '10,786', '115', '10,514', '1.1', '97.5', '964']
['160', '동티모르🇹🇱', '8,781', '19', '7,762', '0.2', '88.4', '6,660']
['161', '적도 기니🇬🇶', '8,708', '120', '8,489', '1.4', '97.5', '6,207']
['162', '베냉🇧🇯', '8,170\n(+30)', '104\n(+1)', '8,000\n(+21)', '1.3', '97.9', '674']
['163', '니카라과🇳🇮', '7,920\n(+224)', '189\n(+1)', '4,225', '2.4', '53.3', '1,196']
['164', '중앙아프리카 공화국🇨🇫', '7,137\n(+8)', '98', '6,859', '1.4', '96.1', '1,478']
['165', '예멘🇾🇪', '6,892\n(+3)', '1,355', '3,980\n(+22)', '19.7', '57.7', '231']
['166', '아이슬란드🇮🇸', '6,630', '30', '6,576', '0.5', '99.2', '19,429']
['167', '감비아🇬🇲', '6,045', '181', '5,837', '3.0', '96.6', '2,501']
['168', '에리트레아🇪🇷', '5,508\n(+87)', '21\n(+2)', '5,016\n(+119)', '0.4', '91.1', '1,553']
['169', '니제르🇳🇪', '5,469', '193', '5,195\n(+17)', '3.5', '95.0', '226']
['170', '부룬디🇧🇮', '5,273\n(+31)', '8', '773', '0.2', '14.7', '443']
['171', '세인트루시아🇱🇨', '5,227\n(+9)', '84\n(+4)', '5,075\n(+10)', '1.6', '97.1', '28,465']
['172', '산마리노🇸🇲', '5,090', '90', '4,999', '1.8', '98.2', '150,010']
['173', '시에라리온🇸🇱', '4,963\n(+84)', '84\n(+2)', '3,279\n(+10)', '1.7', '66.1', '622']
['174', '차드🇹🇩', '4,948\n(+1)', '174', '4,768', '3.5', '96.4', '301']
['175', '지브롤터🇬🇮', '4,323', '94', '4,214', '2.2', '97.5', '128,313']
['176', '바베이도스🇧🇧', '4,045', '47', '3,988', '1.2', '98.6', '14,076']
['177', '코모로🇰🇲', '3,912', '146', '3,745', '3.7', '95.7', '4,499']
['178', '기니비사우🇬🇼', '3,834\n(+9)', '69', '3,565\n(+7)', '1.8', '93.0', '1,948']
['179', '라이베리아🇱🇷', '3,109', '99', '2,169', '3.2', '69.8', '615']
['180', '리히텐슈타인🇱🇮', '3,028', '59', '2,957', '1.9', '97.7', '79,417']
['181', '뉴질랜드🇳🇿', '2,723\n(+3)', '26', '2,673\n(+2)', '1.0', '98.2', '565']
['182', '신트마르턴🇸🇽', '2,582\n(+7)', '32', '2,491\n(+4)', '1.2', '96.5', '60,220']
['183', '모나코🇲🇨', '2,554\n(+5)', '33', '2,487\n(+6)', '1.3', '97.4', '65,083']
['184', '버뮤다🇧🇲', '2,504', '33', '2,461', '1.3', '98.3', '40,207']
['185', '터크스 케이커스 제도🇹🇨', '2,424', '18', '2,389', '0.7', '98.6', '62,608']
['186', '상투메 프린시페🇸🇹', '2,363\n(+1)', '37', '2,315\n(+1)', '1.6', '98.0', '10,782']
['187', '피지🇫🇯', '2,270', '9', '618', '0.4', '27.2', '2,532']
['188', '세인트빈센트 그레나딘🇻🇨', '2,207\n(+11)', '12', '1,941\n(+5)', '0.5', '87.9', '19,894']
['189', '세인트마틴 섬🇲🇫', '2,133', '12', '1,399', '0.6', '65.6', '55,165']
['190', '라오스🇱🇦', '2,067', '3', '1,954', '0.1', '94.5', '284']
['191', '부탄🇧🇹', '1,963\n(+24)', '1', '1,702\n(+17)', '0.1', '86.7', '2,544']
['192', '모리셔스🇲🇺', '1,701', '18', '1,265', '1.1', '74.4', '1,338']
['193', '카리브 네덜란드🇧🇶', '1,634\n(+1)', '17', '1,609\n(+7)', '1.0', '98.5', '62,312']
['194', '맨섬🇮🇲', '1,601\n(+2)', '29', '1,566', '1.8', '97.8', '18,828']
['195', '앤티가 바부다🇦🇬', '1,263', '42', '1,221', '3.3', '96.7', '12,897']

['196', '생바르텔레미🇧🇱', '1,005', '1', '462', '0.1', '46.0', '101,752']
['197', '페로 제도🇫🇴', '769\n(+1)', '1', '755', '0.1', '98.2', '15,738']
['198', '케이맨 제도🇰🇾', '609', '2', '588\n(+1)', '0.3', '96.6', '9,266']
['199', '탄자니아🇹🇿', '509', '21', '183', '4.1', '36.0', '9']
['200', '왈리스 퓌티나🇼🇫', '445', '7', '438', '1.6', '98.4', '-']
['201', '세인트키츠 네비스🇰🇳', '377\n(+27)', '3\n(+1)', '85\n(+10)', '0.8', '22.5', '7,087']
['202', '브루나이🇧🇳', '256', '3', '245', '1.2', '95.7', '585']
['203', '영국령 버진아일랜드🇻🇬', '248', '1', '209', '0.4', '84.3', '8,203']
['204', '도미니카 연방🇩🇲', '191', '0', '189', '-', '99.0', '2,653']
['205', '그레나다🇬🇩', '161', '1', '160', '0.6', '99.4', '1,431']
['206', '뉴칼레도니아🇳🇨', '129', '0', '58', '-', '45.0', '452']
['207', '앵귈라🇦🇮', '109', '0', '109', '-', '100', '7,265']
['208', '포클랜드 제도🇫🇰', '63', '0', '63', '-', '100', '18,103']
['209', '마카오🇲🇴', '53', '0', '51', '-', '96.2', '82']
['210', '그린란드🇬🇱', '50', '0', '40', '-', '80', '881']
['211', '바티칸 시국🇻🇦', '27', '0', '27', '-', '100', '33,708']
['212', '생피에르 미클롱🇵🇲', '26', '0', '25', '-', '96.2', '4,487']
['213', '몬트세랫🇲🇸', '20', '1', '19', '5', '95', '4,006']
['214', '솔로몬 제도🇸🇧', '20', '0', '20', '-', '100', '29']
['215', '서사하라🇪🇭', '10', '1', '8', '10', '80', '17']
['216', '잔담(크루즈)🚢', '9', '2', '7', '22.2', '77.8', '-']
['217', '마셜 제도🇲🇭', '4', '0', '4', '-', '100', '68']
['218', '바누아투🇻🇺', '4', '1', '3', '25', '75', '13']
['219', '사모아🇼🇸', '3', '0', '3', '-', '100', '15']
['220', '세인트헬레나🇸🇭', '2', '0', '2', '-', '100', '329']
['221', '미크로네시아🇫🇲', '1', '0', '1', '-', '100', '9']

In [8]:
import numpy as np
import pandas as pd

all_data_array = np.array(all_data)
data_df = pd.DataFrame(data=all_data_array, columns=['번호', '국가', '확진자', '사망자', '완치', '치명(%)', '완치(%)', '발생률'])

In [9]:
data_df.head(15)

,번호,국가,확진자,사망자,완치,치명(%),완치(%),발생률
0,1,미국🇺🇸,"34,434,803\n(+14,822)","617,875\n(+392)","28,817,134\n(+48,726)",1.8,83.7,"104,032"
1,2,인도🇮🇳,"30,027,850\n(+25,159)","390,691\n(+1,030)","28,987,311\n(+36,585)",1.3,96.5,"21,759"
2,3,브라질🇧🇷,"18,056,639\n(+86,833)","504,897\n(+2,080)","16,388,847\n(+100,455)",2.8,90.8,"84,949"
3,4,프랑스🇫🇷,"5,760,002\n(+2,204)","110,829\n(+51)","5,575,086\n(+8,692)",1.9,96.8,"88,244"
4,5,터키🇹🇷,"5,381,736\n(+6,143)","49,293\n(+57)","5,242,945\n(+5,214)",0.9,97.4,"63,811"
5,6,러시아🇷🇺,"5,350,919","130,347","4,889,450",2.4,91.4,"36,667"
6,7,영국🇬🇧,"4,651,988\n(+11,481)","128,008\n(+27)","4,306,482\n(+2,486)",2.8,92.6,"68,526"
7,8,아르헨티나🇦🇷,"4,298,782\n(+21,387)","90,281\n(+791)","3,928,389\n(+17,554)",2.1,91.4,"95,115"
8,9,이탈리아🇮🇹,"4,254,294\n(+834)","127,322\n(+31)","4,054,008\n(+4,692)",3.0,95.3,"70,363"
9,10,콜롬비아🇨🇴,"3,997,021\n(+28,616)","101,302\n(+720)","3,714,962\n(+29,015)",2.5,92.9,"78,553"
10,11,스페인🇪🇸,"3,768,691\n(+4,040)","80,719\n(+30)","3,564,850\n(+4,816)",2.1,94.6,"80,605"
11,12,독일🇩🇪,"3,731,287\n(+513)","91,082\n(+57)","3,608,100",2.4,96.7,"44,535"
12,13,이란🇮🇷,"3,117,336","83,217","2,771,705",2.7,88.9,"37,114"
13,14,폴란드🇵🇱,"2,879,030","74,858","2,650,773",2.6,92.1,"76,071"
14,15,멕시코🇲🇽,"2,482,784\n(+4,233)","231,505\n(+261)","1,977,071\n(+2,816)",9.3,79.6,"19,256"

In [10]:
data_df.to_excel("covid_df.xlsx", index=True)

In [11]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 221 entries, 0 to 220
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   번호      221 non-null    object
 1   국가      221 non-null    object
 2   확진자     221 non-null    object
 3   사망자     221 non-null    object
 4   완치      221 non-null    object
 5   치명(%)   221 non-null    object
 6   완치(%)   221 non-null    object
 7   발생률     221 non-null    object
dtypes: object(8)
memory usage: 13.9+ KB